/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "4bit_ALU.v:1.1-36.10" *)
module ALU(a, b, op, result);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  (* src = "4bit_ALU.v:2.17-2.18" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "4bit_ALU.v:3.17-3.18" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "4bit_ALU.v:4.17-4.19" *)
  input [1:0] op;
  wire [1:0] op;
  (* src = "4bit_ALU.v:5.22-5.28" *)
  output [3:0] result;
  wire [3:0] result;
  (* src = "4bit_ALU.v:8.16-8.19" *)
  wire [3:0] sum;
  assign _00_ = ~(op[0] | op[1]);
  assign _01_ = op[0] & op[1];
  assign _02_ = ~(a[0] | b[0]);
  assign _03_ = _01_ & ~(_02_);
  assign _04_ = op[1] & ~(op[0]);
  assign _05_ = ~(a[0] & b[0]);
  assign _06_ = _04_ & ~(_05_);
  assign _07_ = _06_ | _03_;
  assign _08_ = op[0] & ~(op[1]);
  assign _09_ = _02_ | ~(_05_);
  assign _10_ = _08_ & ~(_09_);
  assign _11_ = _10_ | _07_;
  assign result[0] = _00_ ? sum[0] : _11_;
  assign _12_ = ~(a[1] | b[1]);
  assign _13_ = _01_ & ~(_12_);
  assign _14_ = ~(a[1] & b[1]);
  assign _15_ = _04_ & ~(_14_);
  assign _16_ = _15_ | _13_;
  assign _17_ = ~(a[1] ^ b[1]);
  assign _18_ = b[0] & ~(a[0]);
  assign _19_ = _18_ ^ _17_;
  assign _20_ = _08_ & ~(_19_);
  assign _21_ = _20_ | _16_;
  assign result[1] = _00_ ? sum[1] : _21_;
  assign _22_ = ~(a[2] | b[2]);
  assign _23_ = _01_ & ~(_22_);
  assign _24_ = ~(a[2] & b[2]);
  assign _25_ = _04_ & ~(_24_);
  assign _26_ = _25_ | _23_;
  assign _27_ = _22_ | ~(_24_);
  assign _28_ = b[1] | ~(a[1]);
  assign _29_ = _17_ & ~(_18_);
  assign _30_ = _28_ & ~(_29_);
  assign _31_ = _30_ ^ _27_;
  assign _32_ = _08_ & ~(_31_);
  assign _33_ = _32_ | _26_;
  assign result[2] = _00_ ? sum[2] : _33_;
  assign _34_ = ~(a[3] | b[3]);
  assign _35_ = _01_ & ~(_34_);
  assign _36_ = ~(a[3] & b[3]);
  assign _37_ = _04_ & ~(_36_);
  assign _38_ = _37_ | _35_;
  assign _39_ = _34_ | ~(_36_);
  assign _40_ = b[2] | ~(a[2]);
  assign _41_ = _27_ & ~(_30_);
  assign _42_ = _40_ & ~(_41_);
  assign _43_ = _42_ ^ _39_;
  assign _44_ = _08_ & ~(_43_);
  assign _45_ = _44_ | _38_;
  assign result[3] = _00_ ? sum[3] : _45_;
  (* module_not_derived = 32'd1 *)
  (* src = "4bit_ALU.v:13.16-19.6" *)
  adder_4bit add_unit (
    .a(a),
    .b(b),
    .cin(1'h0),
    .sum(sum)
  );
endmodule

(* src = "adder_4bit.v:1.1-15.10" *)
module adder_4bit(a, b, cin, sum, cout);
  (* src = "adder_4bit.v:2.17-2.18" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "adder_4bit.v:3.17-3.18" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "adder_4bit.v:8.10-8.12" *)
  wire c1;
  (* src = "adder_4bit.v:8.14-8.16" *)
  wire c2;
  (* src = "adder_4bit.v:8.18-8.20" *)
  wire c3;
  (* src = "adder_4bit.v:4.11-4.14" *)
  input cin;
  wire cin;
  (* src = "adder_4bit.v:6.12-6.16" *)
  output cout;
  wire cout;
  (* src = "adder_4bit.v:5.18-5.21" *)
  output [3:0] sum;
  wire [3:0] sum;
  (* module_not_derived = 32'd1 *)
  (* src = "adder_4bit.v:11.16-11.76" *)
  full_adder fa0 (
    .a(a[0]),
    .b(b[0]),
    .cin(cin),
    .cout(c1),
    .sum(sum[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder_4bit.v:12.16-12.76" *)
  full_adder fa1 (
    .a(a[1]),
    .b(b[1]),
    .cin(c1),
    .cout(c2),
    .sum(sum[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder_4bit.v:13.16-13.76" *)
  full_adder fa2 (
    .a(a[2]),
    .b(b[2]),
    .cin(c2),
    .cout(c3),
    .sum(sum[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder_4bit.v:14.16-14.78" *)
  full_adder fa3 (
    .a(a[3]),
    .b(b[3]),
    .cin(c3),
    .cout(cout),
    .sum(sum[3])
  );
endmodule

(* src = "full_adder.v:1.1-10.10" *)
module full_adder(a, b, cin, sum, cout);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "full_adder.v:2.11-2.12" *)
  input a;
  wire a;
  (* src = "full_adder.v:3.11-3.12" *)
  input b;
  wire b;
  (* src = "full_adder.v:4.11-4.14" *)
  input cin;
  wire cin;
  (* src = "full_adder.v:6.12-6.16" *)
  output cout;
  wire cout;
  (* src = "full_adder.v:5.12-5.15" *)
  output sum;
  wire sum;
  assign _0_ = b & a;
  assign _1_ = ~(b ^ a);
  assign _2_ = cin & ~(_1_);
  assign cout = _2_ | _0_;
  assign sum = ~(_1_ ^ cin);
endmodule
