/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "full_adder.v:1.1-10.10" *)
module full_adder(a, b, cin, sum, cout);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "full_adder.v:2.11-2.12" *)
  input a;
  wire a;
  (* src = "full_adder.v:3.11-3.12" *)
  input b;
  wire b;
  (* src = "full_adder.v:4.11-4.14" *)
  input cin;
  wire cin;
  (* src = "full_adder.v:6.12-6.16" *)
  output cout;
  wire cout;
  (* src = "full_adder.v:5.12-5.15" *)
  output sum;
  wire sum;
  assign _0_ = ~(b ^ a);
  assign sum = ~(_0_ ^ cin);
  assign _1_ = b & a;
  assign _2_ = cin & ~(_0_);
  assign cout = _2_ | _1_;
endmodule
